x = int(input('Deseja a tabuada de que valor? '))
print('=' * 12)
print('Tabuada do {}' .format(x))
print('=' * 12)
print(f' {x} x {1:2} = {x * 1:2}') # O :2 faz com que tenha alocado 2 espaços, assim fica alinhado com o 10.
print(f' {x} x {2:2} = {x * 2:2}')
print(f' {x} x {3:2} = {x * 3:2}')
print(f' {x} x {4:2} = {x * 4:2}')
print(f' {x} x {5:2} = {x * 5:2}')
print(f' {x} x {6:2} = {x * 6:2}')
print(f' {x} x {7:2} = {x * 7:2}')
print(f' {x} x {8:2} = {x * 8:2}')
print(f' {x} x {9:2} = {x * 9:2}')
print(f' {x} x {10:2} = {x * 10:2}')
print('=' * 12)
